---
title: "Mixscape sgRNA GEX effects CTR02"
author: "Eric Wang"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(Seurat)
library(ggplot2)
library(ggrepel)
library(gridExtra)
library(grid)
library(pheatmap)
library(viridis)
library(patchwork)
library(scales)
library(DESeq2)
knitr::opts_chunk$set(echo = TRUE)

source("../functions/plotting_fxns.R")
source("../functions/scRNA_seq_analysis_functions.R")
theme_set(theme_Publication())
```

## **Data Import**

```{r}
data <- readRDS("processing/CTR02_seurat_SCT_CRISPRumi9.rds")
```

Add some metadata columns

```{r}
# filter data to only include cells with one guide
data <- subset(data, subset = num_features == 1)
data$feature_gene <- gsub("\\..*","",data$feature_call)
# split hash ID into separate organ and CD62L status
hashSplit <- data@meta.data %>%
  dplyr::select(hash.ID) %>%
  separate(hash.ID,c("organ","CD62L_status"), sep = "-")
data$organ <- hashSplit$organ
data$CD62L_status <- hashSplit$CD62L_status

# create metadata column where gene sgRNA retain name but all NTC/NCC guides are merged
data$feature_call_control <- gsub("NTC\\.\\d+$|NCC\\.\\d+$","control",data$feature_call)
data$feature_gene <- gsub("NTC|NCC","control",data$feature_gene)
```

## **Mixscape**

### Calculat Perturbation Signatures and Demultiplex

```{r}
data <- CalcPerturbSig(data,
                       assay = "SCT",
                       slot = "data",
                       gd.class = "feature_gene",
                       nt.cell.class = "control",
                       ndims=40,
                       num.neighbors = 20,
                       new.assay.name = "PRTB")

# Prepare PRTB assay for dimensionality reduction: 
# Normalize data, find variable features and center data.
DefaultAssay(object = data) <- 'PRTB'

# Use variable features from SCT assay.
VariableFeatures(object = data) <- VariableFeatures(object = data[["SCT"]])
data <- ScaleData(object = data, do.scale = F, do.center = T)

# Run PCA to reduce the dimensionality of the data.
data <- RunPCA(object = data, reduction.key = 'prtbpca', reduction.name = 'prtbpca')

# Run UMAP to visualize clustering in 2-D.
data <- RunUMAP(
  object = data, 
  dims = 1:40, 
  reduction = 'prtbpca', 
  reduction.key = 'prtbumap', 
  reduction.name = 'prtbumap')
```

```{r, fig.height=8, fig.width=10}
# Generate plots to check if clustering is driven by biological replicate ID, 
# cell cycle phase or target gene class.
q1 <- DimPlot(
  object = data, 
  group.by = 'hash.ID', 
  reduction = 'prtbumap', 
  pt.size = 0.2, cols = "Dark2", label = F, repel = T) +
  scale_color_brewer(palette = "Dark2") +
  ggtitle("Cell Type") +
  ylab("UMAP 2") +
  xlab("UMAP 1")

q2 <- DimPlot(
  object = data, 
  group.by = 'Phase', 
  reduction = 'prtbumap', 
  pt.size = 0.2, label = F, repel = T) +
  ggtitle("Cell Cycle Phase") +
  ylab("UMAP 2") +
  xlab("UMAP 1")

q3 <- DimPlot(
  object = data,
  group.by = 'feature_gene',
  reduction = 'prtbumap', 
  split.by = "feature_gene", 
  ncol = 1, 
  pt.size = 0.2) +
  ggtitle("Perturbation Status") +
  ylab("UMAP 2") +
  xlab("UMAP 1")

# Visualize plots.
(q1/q2 + plot_layout(guides = 'auto') | q3)
```

```{r}
# Run mixscape.
data <- RunMixscape(
  object = data, 
  assay = "PRTB", 
  slot = "scale.data", 
  labels = "feature_gene", 
  nt.class.name = "control", 
  min.de.genes = 5,
  logfc.threshold = 0.5,
  iter.num = 10, 
  de.assay = "SCT", 
  verbose = T,
  prtb.type = "KO")

# export mixscape perturbation classifications
write.csv(data@meta.data, "analysis_outs/mixscape_classification_metadata.csv")

# create table with frequencies of perturbation per guide
resTable <- data@meta.data %>% 
  group_by(feature_call) %>%
  mutate(sgRNA_count = sum(n())) %>%
  group_by(feature_call, sgRNA_count, mixscape_class) %>%
  summarise(mixscale_class_count = n()) %>%
  mutate(mixscale_class_freq = mixscale_class_count/sgRNA_count) %>%
  filter(mixscape_class != "control") %>%
  mutate(mixscape_class = gsub(".*? ","",mixscape_class)) %>%
  mutate(mixscape_class = factor(mixscape_class,c("NP","KO"))) %>%
  separate(feature_call, c("gene","sgRNA_number"), sep = "\\.")
  

ggplot(resTable, aes(x = sgRNA_number, y = mixscale_class_freq*100, fill= mixscape_class)) +
  geom_bar(stat= "identity") +
  facet_wrap(~gene) +
  scale_fill_manual(values = c("grey79","coral1")) + 
  ylab("% of cells") +
  xlab("sgRNA")
```

### Check Perturbation Scores

```{r, fig.width=14, fig.height=4}
p1 <- PlotPerturbScore(object = data, 
                 target.gene.class = "feature_gene",
                 target.gene.ident = "Ifngr1", 
                 mixscape.class = "mixscape_class", 
                 col = "coral2") +labs(fill = "mixscape_class")
p2 <- PlotPerturbScore(object = data, 
                 target.gene.class = "feature_gene",
                 target.gene.ident = "Tgfbr2", 
                 mixscape.class = "mixscape_class", 
                 col = "coral2") +labs(fill = "mixscape_class")

p1+p2
```

```{r, fig.width=12, fig.height=6}
p1 <- VlnPlot(data, "mixscape_class_p_ko", idents = c("control","Ifngr1 KO","Ifngr1 NP"))
p2 <- VlnPlot(data, "mixscape_class_p_ko", idents = c("control","Tgfbr2 KO","Tgfbr2 NP"))
p1|p2
```

```{r, fig.height=12, fig.width=10}
# Run DE analysis and visualize results on a heatmap ordering cells by their posterior 
# probability values.
Idents(data) <- "feature_gene"
MixscapeHeatmap(object = data, 
                ident.1 = "control", 
                ident.2 = "Ifngr1", 
                balanced = F, 
                assay = "SCT", 
                max.genes = 20, angle = 0, 
                group.by = "mixscape_class", 
                max.cells.group = 300, 
                size=6.5) + NoLegend()

MixscapeHeatmap(object = data, 
                ident.1 = "control", 
                ident.2 = "Tgfbr2", 
                balanced = F, 
                order.by.prob = T,
                assay = "SCT", 
                max.genes = 40, angle = 0, 
                group.by = "mixscape_class", 
                max.cells.group = 300, 
                size=6.5) + NoLegend()
```
